version: '3'

services:
  pandell-testing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pandell-testing
    restart: no
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  staticbuild:
