version: '3'

services:
  pandell-testing:
    image: vladimirovsk/pandell-test:latest
    container_name: pandell-testing
    restart: no
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  staticbuild:
