name: Bitcoders Front

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
#      - name: Login in Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Build docker
#        run: docker build . -t vladimirovsk/bitcoders-react:master
#      - name: Publish to Docker
#        run: |
#          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#          docker push vladimirovsk/bitcoders-react:master
#  deploy:
#    needs: [build, test]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy to server
#        uses: appleboy/ssh-action@v0.1.4
#        with:
#          host: 65.108.199.29
#          username: svladimirov
#          password: ${{ secrets.SSH_PASSWORD }}
##          key: ${{ secrets.SERVER_SECRET }}
#          port: 33100
#          script: |
#            cd project/BitCodersReact
#            git checkout dev
#            git pull
#            docker-compose up -d --build
              
              
